### ISSUE TITLE
import_reference_docs.js fails on empty extension component directory

### ISSUE THREAD

**Issue by elljoh** [ampproject/docs#83]
The following `ampproject/amphtml` extension breaks at [import_reference_docs.js#L167](https://github.com/ampproject/docs/blob/master/_scripts/import_reference_docs.js#L167)
- [extensions/amp-live-list/0.1](https://github.com/ampproject/amphtml/tree/master/extensions/amp-live-list/0.1)
 - `amp-live-list` does not have `type.file` contents.

To reproduce:
- follow [README](https://github.com/ampproject/docs#import-the-reference-docs)

```
TypeError: Cannot read property 'path' of undefined
    at /Users/jellis/dev/projects/yieldbot/amphtml.docs/_scripts/import_reference_docs.js:167:29
    at /Users/jellis/dev/projects/yieldbot/amphtml.docs/node_modules/octonode/lib/octonode/repo.js:471:18
    at Client.errorHandle (/Users/jellis/dev/projects/yieldbot/amphtml.docs/node_modules/octonode/lib/octonode/client.js:196:14)
    at Request._callback (/Users/jellis/dev/projects/yieldbot/amphtml.docs/node_modules/octonode/lib/octonode/client.js:210:24)
    at Request.self.callback (/Users/jellis/dev/projects/yieldbot/amphtml.docs/node_modules/request/request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/jellis/dev/projects/yieldbot/amphtml.docs/node_modules/request/request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
```

**Comment by elljoh** [comment]
@erwinmombay if you add a documentation file here:

- https://github.com/ampproject/amphtml/tree/master/extensions/amp-live-list

I think we can just close this issue.
