### ISSUE TITLE
`grow build` occasionally fails on Travis

### ISSUE THREAD

**Issue by rsimha** [ampproject/docs#968]
I'm seeing the occasional error from `grow build` on Travis.

Any idea what is causing this?

```
Building locales: None, en, de, es,
[12:30:08] Compiled: ru (8/320)
[12:30:08] Compiled: fr (12/320)
[12:30:08] Compiled: pt_BR (185/320)
[12:30:08] Compiled: zh_CN (188/320)
[12:30:08] Compiled: tr (8/320)
[12:30:08] Compiled: ko (186/320)
[12:30:08] Compiled: it (175/320)
[12:30:08] Compiled: id (187/320)
[12:30:08] Compiled: ar (12/320)
[12:30:08] Compiled: ja (186/320)
[12:30:08] Compiled: es (190/320)
[12:30:10] Using gulpfile ~/build/ampproject/docs/gulpfile.js
[12:30:10] Starting 'build'...
[12:30:10] Starting 'update-blog-links'...
[12:30:10] Starting 'optimize-images'...
[12:30:10] Starting 'sass'...
[12:30:10] Starting 'build-examples'...
[12:30:10] Starting 'generate-asset-manifest'...
[12:30:10] Starting 'import-docs'...
[12:30:10] Finished 'build-examples' after 603 ms
[12:30:12] Finished 'update-blog-links' after 2.9 s
[12:30:19] Finished 'import-docs' after 9.65 s
[12:30:19] Starting 'update-platforms-page'...
[12:30:19] Finished 'generate-asset-manifest' after 9.67 s
[12:30:22] Finished 'update-platforms-page' after 2.62 s
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:4536) UnhandledPromiseRejectionWarning: Error: Phantom process stopped with exit code 0
    at commands.forEach.command (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (/home/travis/build/ampproject/docs/node_modules/phantom/lib/phantom.js:148:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:440:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:4536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
[12:30:24] Finished 'optimize-images' after 14 s
[12:30:26] Finished 'sass' after 16 s
[12:30:26] Finished 'build' after 16 s
Building: 1464/1464 (in 0:03:23.2)                                              
Unable to find remote index: index.proto.json
Action                                                             Path                                                              Last deployed   By 
=======================================================================================================================================================
add      /404.html                                                                                                                                      
add      /about/amp-design-principles/index.html                                                                                                        
add      /about/benefits/index.html                                                                                                                     
add      /amp-conf-2017/index.html                                                                                                                      
add      /amp-conf/accessibility/index.html                                                                                                             
add      /amp-conf/code-of-conduct/index.html                                                                                                           
add      /amp-conf/index.html                                                                                                                           
add      /amp-roadshow/index.html                                                                                                                       
add      /case-studies/advertisers/index.html                                                                                                           
add      /case-studies/bmw/index.html                                                                                                                   
add      /case-studies/cnbc/index.html                                                                                                                  
add      /case-studies/consumers_advocate/index.html                                                                                                    
add      /case-studies/ecommerce/index.html                                                                                                             
add      /case-studies/eski_mobi/index.html                                                                                                             
add      /case-studies/event_ticket_center/index.html                                                                                                   
add      /case-studies/fastcommerce/index.html                                                                                                          
add      /case-studies/gizmodo/index.html                                                                                                               
add      /case-studies/greenweez/index.html                                                                                                             
add      /case-studies/grupo/index.html                                                                                                                 
add      /case-studies/hearst/index.html                                                                                                                
add      /case-studies/index.html                                                                                                                       
add      /case-studies/indiatoday/index.html                                                                                                            
add      /case-studies/innkeepers/index.html                                                                                                            
add      /case-studies/merchology/index.html                                                                                                            
add      /case-studies/milestone/index.html                                                                                                             
add      /case-studies/nobroker/index.html                                                                                                              
add      /case-studies/plista/index.html                                                                                                                
add      /case-studies/publishers/index.html                                                                                                            
add      /case-studies/relay_media/index.html                                                                                                           
add      /case-studies/slate/index.html                                                                                                                 
add      /case-studies/teads/index.html                                                                                                                 
add      /case-studies/terra/index.html                                                                                                                 
add      /case-studies/transunion/index.html                                                                                                            
add      /case-studies/triplelift/index.html                                                                                                            
add      /case-studies/us_xpress/index.html                                                                                                             
add      /case-studies/washingtonpost/index.html                                                                                                        
add      /case-studies/wego/index.html                                                                                                                  
add      /case-studies/wired/index.html                                                                                                                 
add      /case-studies/wompmobile/index.html                                                                                                            
add      /contribute/index.html                                                                                                                         
add      /docs/ads/a4a_spec.html                                                                                                                        
add      /docs/ads/adnetwork_integration.html                                                                                                           
add      /docs/ads/ads_vendors.html                                                                                                                     
add      /docs/ads/amphtml_ads.html                                                                                                                     
add      /docs/ads/amphtml_ads/create_shell.html                                                                                                        
add      /docs/ads/amphtml_ads/image_ad.html                                                                                                            
add      /docs/ads/amphtml_ads/summary.html                                                                                                             
add      /docs/ads/amphtml_ads/track_views.html                                                                                                         
add      /docs/ads/amphtml_ads/validate.html                                                                                                            
add      /docs/ads/create_amphtml_ad.html                                                                                                               
add      /docs/ads/index.html                                                                                                                           
add      /docs/ads/integration-guide.html                                                                                                               
add      /docs/ads/introduction_ads.html                                                                                                                
add      /docs/ads/monetization.html                                                                                                                    
add      /docs/analytics/amp-managing-user-state.html                                                                                                   
add      /docs/analytics/analytics-vendors.html                                                                                                         
add      /docs/analytics/analytics_amp.html                                                                                                             
add      /docs/analytics/analytics_basics.html                                                                                                          
add      /docs/analytics/deep_dive_analytics.html                                                                                                       
add      /docs/analytics/index.html                                                                                                                     
add      /docs/analytics/integrating-analytics.html                                                                                                     
add      /docs/analytics/use_cases.html                                                                                                                 
add      /docs/blank/index.html                                                                                                                         
add      /docs/contribute/governance/index.html                                                                                                         
add      /docs/contribute/index.html                                                                                                                    
add      /docs/design/amp-html-layout.html                                                                                                              
add      /docs/design/amp_story_best_practices.html                                                                                                     
add      /docs/design/index.html                                                                                                                        
add      /docs/design/responsive/art_direction.html                                                                                                     
add      /docs/design/responsive/control_layout.html                                                                                                    
add      /docs/design/responsive/custom_fonts.html                                                                                                      
add      /docs/design/responsive/placeholders.html                                                                                                      
add      /docs/design/responsive/responsive_design.html                                                                                                 
add      /docs/design/responsive/style_pages.html                                                                                                       
add      /docs/design/responsive_amp.html                                                                                                               
add      /docs/design/visual_story.html                                                                                                                 
add      /docs/design/visual_story/add_more_pages.html                                                                                                  
add      /docs/design/visual_story/animating_elements.html                                                                                              
add      /docs/design/visual_story/congratulations.html                                                                                                 
add      /docs/design/visual_story/create_bookend.html                                                                                                  
add      /docs/design/visual_story/create_cover_page.html                                                                                               
add      /docs/design/visual_story/parts_of_story.html                                                                                                  
add      /docs/design/visual_story/setting_up.html                                                                                                      
add      /docs/design/visual_story/validation.html                                                                                                      
add      /docs/fundamentals/add_advanced.html                                                                                                           
add      /docs/fundamentals/add_advanced/adding_carousels.html                                                                                          
add      /docs/fundamentals/add_advanced/adding_components.html                                                                                         
add      /docs/fundamentals/add_advanced/congratulations.html                                                                                           
add      /docs/fundamentals/add_advanced/fonts.html                                                                                                     
add      /docs/fundamentals/add_advanced/navigating.html                                                                                                
add      /docs/fundamentals/add_advanced/review_code.html                                                                                               
add      /docs/fundamentals/add_advanced/setting_up.html                                                                                                
add      /docs/fundamentals/add_advanced/tracking_data.html                                                                                             
add      /docs/fundamentals/amp-cors-requests.html                                                                                                      
add      /docs/fundamentals/converting.html                                                                                                             
add      /docs/fundamentals/converting/building-page.html                                                                                               
add      /docs/fundamentals/converting/congratulations.html                                                                                             
add      /docs/fundamentals/converting/discoverable.html                                                                                                
add      /docs/fundamentals/converting/resolving-errors.html                                                                                            
add      /docs/fundamentals/converting/setting-up.html                                                                                                  
add      /docs/fundamentals/discovery.html                                                                                                              
add      /docs/fundamentals/engagement.html                                                                                                             
add      /docs/fundamentals/how_cached.html                                                                                                             
add      /docs/fundamentals/index.html                                                                                                                  
add      /docs/fundamentals/spec.html                                                                                                                   
add      /docs/fundamentals/spec/amp-boilerplate.html                                                                                                   
add      /docs/fundamentals/third_party_components.html                                                                                                 
add      /docs/fundamentals/validate.html                                                                                                               
add      /docs/getting_started/create.html                                                                                                              
add      /docs/getting_started/create/basic_markup.html                                                                                                 
add      /docs/getting_started/create/include_image.html                                                                                                
add      /docs/getting_started/create/prepare_for_discovery.html                                                                                        
add      /docs/getting_started/create/presentation_layout.html                                                                                          
add      /docs/getting_started/create/preview_and_validate.html                                                                                         
add      /docs/getting_started/create/publish.html                                                                                                      
add      /docs/getting_started/index.html                                                                                                               
add      /docs/getting_started/quickstart.html                                                                                                          
add      /docs/index.html                                                                                                                               
add      /docs/integration/index.html                                                                                                                   
add      /docs/integration/integrate-with-apps.html                                                                                                     
add      /docs/integration/integrate-your-tech.html                                                                                                     
add      /docs/integration/pwa-amp.html                                                                                                                 
add      /docs/integration/pwa-amp/amp-as-pwa.html                                                                                                      
add      /docs/integration/pwa-amp/amp-in-pwa.html                                                                                                      
add      /docs/integration/pwa-amp/amp-to-pwa.html                                                                                                      
add      /docs/integration/supported_integrations.html                                                                                                  
add      /docs/interaction_dynamic/amp-actions-and-events.html                                                                                          
add      /docs/interaction_dynamic/index.html                                                                                                           
add      /docs/interaction_dynamic/interactivity.html                                                                                                   
add      /docs/interaction_dynamic/interactivity/advanced-interactivity.html                                                                            
add      /docs/interaction_dynamic/interactivity/get-familiar.html                                                                                      
add      /docs/interaction_dynamic/interactivity/prereqs-setup.html                                                                                     
add      /docs/interaction_dynamic/interactivity/remote-data.html                                                                                       
add      /docs/interaction_dynamic/interactivity/wrapping-up.html                                                                                       
add      /docs/interaction_dynamic/live_blog.html                                                                                                       
add      /docs/interaction_dynamic/login_requiring.html                                                                                                 
add      /docs/interaction_dynamic/login_requiring/add_comment.html                                                                                     
add      /docs/interaction_dynamic/login_requiring/login.html                                                                                           
add      /docs/interaction_dynamic/login_requiring/logout.html                                                                                          
add      /docs/interaction_dynamic/login_requiring/summary.html                                                                                         
add      /docs/media/amp_replacements.html                                                                                                              
add      /docs/media/iframes.html                                                                                                                       
add      /docs/media/index.html                                                                                                                         
add      /docs/reference/common_attributes.html                                                                                                         
add      /docs/reference/components.html                                                                                                                
add      /docs/reference/components/amp-3q-player.html                                                                                                  
add      /docs/reference/components/amp-access-laterpay.html                                                                                            
add      /docs/reference/components/amp-access.html                                                                                                     
add      /docs/reference/components/amp-accordion.html                                                                                                  
add      /docs/reference/components/amp-ad-exit.html                                                                                                    
add      /docs/reference/components/amp-ad.html                                                                                                         
add      /docs/reference/components/amp-addthis.html                                                                                                    
add      /docs/reference/components/amp-analytics.html                                                                                                  
add      /docs/reference/components/amp-anim.html                                                                                                       
add      /docs/reference/components/amp-animation.html                                                                                                  
add      /docs/reference/components/amp-apester-media.html                                                                                              
add      /docs/reference/components/amp-app-banner.html                                                                                                 
add      /docs/reference/components/amp-audio.html                                                                                                      
add      /docs/reference/components/amp-auto-ads.html                                                                                                   
add      /docs/reference/components/amp-beopinion.html                                                                                                  
add      /docs/reference/components/amp-bind.html                                                                                                       
add      /docs/reference/components/amp-bodymovin-animation.html                                                                                        
add      /docs/reference/components/amp-brid-player.html                                                                                                
add      /docs/reference/components/amp-brightcove.html                                                                                                 
add      /docs/reference/components/amp-byside-content.html                                                                                             
add      /docs/reference/components/amp-call-tracking.html                                                                                              
add      /docs/reference/components/amp-carousel.html                                                                                                   
add      /docs/reference/components/amp-consent.html                                                                                                    
add      /docs/reference/components/amp-dailymotion.html                                                                                                
add      /docs/reference/components/amp-date-picker.html                                                                                                
add      /docs/reference/components/amp-dynamic-css-classes.html                                                                                        
add      /docs/reference/components/amp-experiment.html                                                                                                 
add      /docs/reference/components/amp-facebook-comments.html                                                                                          
add      /docs/reference/components/amp-facebook-like.html                                                                                              
add      /docs/reference/components/amp-facebook-page.html                                                                                              
add      /docs/reference/components/amp-facebook.html                                                                                                   
add      /docs/reference/components/amp-fit-text.html                                                                                                   
add      /docs/reference/components/amp-font.html                                                                                                       
add      /docs/reference/components/amp-form.html                                                                                                       
add      /docs/reference/components/amp-fx-collection.html                                                                                              
add      /docs/reference/components/amp-fx-flying-carpet.html                                                                                           
add      /docs/reference/components/amp-geo.html                                                                                                        
add      /docs/reference/components/amp-gfycat.html                                                                                                     
add      /docs/reference/components/amp-gist.html                                                                                                       
add      /docs/reference/components/amp-google-vrview-image.html                                                                                        
add      /docs/reference/components/amp-hulu.html                                                                                                       
add      /docs/reference/components/amp-iframe.html                                                                                                     
add      /docs/reference/components/amp-ima-video.html                                                                                                  
add      /docs/reference/components/amp-image-lightbox.html                                                                                             
add      /docs/reference/components/amp-img.html                                                                                                        
add      /docs/reference/components/amp-imgur.html                                                                                                      
add      /docs/reference/components/amp-instagram.html                                                                                                  
add      /docs/reference/components/amp-install-serviceworker.html                                                                                      
add      /docs/reference/components/amp-izlesene.html                                                                                                   
add      /docs/reference/components/amp-jwplayer.html                                                                                                   
add      /docs/reference/components/amp-kaltura-player.html                                                                                             
add      /docs/reference/components/amp-layout.html                                                                                                     
add      /docs/reference/components/amp-lightbox-gallery.html                                                                                           
add      /docs/reference/components/amp-lightbox.html                                                                                                   
add      /docs/reference/components/amp-list.html                                                                                                       
add      /docs/reference/components/amp-live-list.html                                                                                                  
add      /docs/reference/components/amp-mathml.html                                                                                                     
add      /docs/reference/components/amp-mustache.html                                                                                                   
add      /docs/reference/components/amp-nexxtv-player.html                                                                                              
add      /docs/reference/components/amp-o2-player.html                                                                                                  
add      /docs/reference/components/amp-ooyala-player.html                                                                                              
add      /docs/reference/components/amp-pinterest.html                                                                                                  
add      /docs/reference/components/amp-pixel.html                                                                                                      
add      /docs/reference/components/amp-playbuzz.html                                                                                                   
add      /docs/reference/components/amp-position-observer.html                                                                                          
add      /docs/reference/components/amp-reach-player.html                                                                                               
add      /docs/reference/components/amp-reddit.html                                                                                                     
add      /docs/reference/components/amp-riddle-quiz.html                                                                                                
add      /docs/reference/components/amp-selector.html                                                                                                   
add      /docs/reference/components/amp-sidebar.html                                                                                                    
add      /docs/reference/components/amp-social-share.html                                                                                               
add      /docs/reference/components/amp-soundcloud.html                                                                                                 
add      /docs/reference/components/amp-springboard-player.html                                                                                         
add      /docs/reference/components/amp-sticky-ad.html                                                                                                  
add      /docs/reference/components/amp-story.html                                                                                                      
add      /docs/reference/components/amp-timeago.html                                                                                                    
add      /docs/reference/components/amp-twitter.html                                                                                                    
add      /docs/reference/components/amp-user-notification.html                                                                                          
add      /docs/reference/components/amp-video.html                                                                                                      
add      /docs/reference/components/amp-vimeo.html                                                                                                      
add      /docs/reference/components/amp-vine.html                                                                                                       
add      /docs/reference/components/amp-viz-vega.html                                                                                                   
add      /docs/reference/components/amp-vk.html                                                                                                         
add      /docs/reference/components/amp-web-push.html                                                                                                   
add      /docs/reference/components/amp-wistia-player.html                                                                                              
add      /docs/reference/components/amp-youtube.html                                                                                                    
add      /docs/reference/experimental.html                                                                                                              
add      /docs/troubleshooting/amp-cache-debugging.html                                                                                                 
add      /docs/troubleshooting/index.html                                                                                                               
add      /docs/troubleshooting/validation_errors.html                                                                                                   
add      /es/404/index.html                                                                                                                             
add      /es/about/amp-design-principles/index.html                                                                                                     
add      /es/about/benefits/index.html                                                                                                                  
add      /es/amp-conf/index.html                                                                                                                        
add      /es/amp-roadshow/index.html                                                                                                                    
add      /es/case-studies/advertisers/index.html                                                                                                        
add      /es/case-studies/bmw/index.html                                                                                                                
add      /es/case-studies/cnbc/index.html                                                                                                               
add      /es/case-studies/consumers_advocate/index.html                                                                                                 
add      /es/case-studies/ecommerce/index.html                                                                                                          
add      /es/case-studies/eski_mobi/index.html                                                                                                          
add      /es/case-studies/event_ticket_center/index.html                                                                                                
add      /es/case-studies/fastcommerce/index.html                                                                                                       
add      /es/case-studies/gizmodo/index.html                                                                                                            
add      /es/case-studies/greenweez/index.html                                                                                                          
add      /es/case-studies/grupo/index.html                                                                                                              
add      /es/case-studies/hearst/index.html                                                                                                             
add      /es/case-studies/indiatoday/index.html                                                                                                         
add      /es/case-studies/innkeepers/index.html                                                                                                         
add      /es/case-studies/merchology/index.html                                                                                                         
add      /es/case-studies/milestone/index.html                                                                                                          
add      /es/case-studies/nobroker/index.html                                                                                                           
add      /es/case-studies/plista/index.html                                                                                                             
add      /es/case-studies/publishers/index.html                                                                                                         
add      /es/case-studies/relay_media/index.html                                                                                                        
add      /es/case-studies/slate/index.html                                                                                                              
add      /es/case-studies/teads/index.html                                                                                                              
add      /es/case-studies/terra/index.html                                                                                                              
add      /es/case-studies/transunion/index.html                                                                                                         
add      /es/case-studies/triplelift/index.html                                                                                                         
add      /es/case-studies/us_xpress/index.html                                                                                                          
add      /es/case-studies/washingtonpost/index.html                                                                                                     
add      /es/case-studies/wego/index.html                                                                                                               
add      /es/case-studies/wired/index.html                                                                                                              
add      /es/case-studies/wompmobile/index.html                                                                                                         
add      /es/contribute/index.html                                                                                                                      
add      /es/docs/ads/a4a_spec.html                                                                                             : Resource temporarily unavailable
/home/travis/.travis/job_stages: line 169:  4525 Terminated              travis_jigger $! $timeout $cmd
```

**Comment by bpaduch** [comment]
Performed a `npm ls phantom` and it looks like `amp-by-example@0.1.5` is using it.  We use `amp-by-example` to [build our embedded samples](https://github.com/ampproject/docs/blob/master/gulpfile.js#L15). Maybe @sebastianbenz  can shed some insight on these errors?

**Comment by pbakaus** [comment]
interestingly, I don't think that that's whats causing the build to fail...I see those errors all the time and I don't think they produce a status code of 1.

The line at the bottom looks weirder, the resource unavailable thing..

**Comment by rsimha** [comment]
Seems like there are two issues at play: A synchronization error in `gulpfile.js`, and a rate limiting problem due to using an external service.
